services:
  nuxt-app:
    container_name: nuxt_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    container_name: postgres_nuxt
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
